# Lychee checks alls docs for dead links and let the pipeline fail if any are found.
name: Lychee Link Checker
on:
  workflow_call:
permissions:
  contents: read
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Restore Lychee Cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: lychee-cache-${{ github.ref_name }}
          restore-keys: lychee-cache-
      - name: Dead Link Check
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          fail: true
          args: --cache --max-retries 5 --retry-wait-time 5 --max-cache-age 30d docs/
